### ISSUE TITLE
NaN dans le compteur sur navigateurs Safari et Edge

### ISSUE THREAD

**Issue by qperez** [bibnumbcu/casuhalathon#1]
Bonjour @bibnumbcu ,

Merci pour votre contribution et la mise à disposition de votre jauge. Nous l'avons adapté et intégré dans notre [serveur Hal](https://hal.mines-ales.fr/page/casuhalathon)
En revanche nous avons relevé un bug sur l'affichage du compteur, celui-ci affiche "NaN" sur les navigateurs Edge et Safari. 

Nous avons localisé le bug et l'avons fixé. Il est lié à un format de date non reconnu par certains navigateurs dans le fichier [jauge.php, ligne 17](https://github.com/bibnumbcu/casuhalathon/blob/8a8296ae19e53fe52cd9e1c499f2573d6af4855d/jauge.php#L17)

Nous vous proposons notre correction : 
Remplacer la ligne 17 dans jauge.php
`$countDownDate = "Jun 11, 2021 24:00:00";`
par
`$countDownDate = "2021-06-11T24:00:00";`

**Comment by bibnumbcu** [comment]
Merci pour le retour, c'est corrigé.
